services:
  front:
    build: ./studybed-app
    command: "npm run start"
    environment:
      - PORT=4200
      - HOST=0.0.0.0
      - BACKEND_BROWSER_API=http://localhost:3000
      - BACKEND_SERVER_API=http://backend:3000
    volumes:
      - ./studybed-app:/usr/src/app
      - /usr/src/app/node_modules/
    ports:
      - "4200:4200"
    depends_on:
      - backend

  backend:
    build: ./studybed-api
    command: "npm run start:dev"
    environment:
      - PORT=3000
      - HOST=0.0.0.0
      - MARKDOWN_DB_PATH=file:/usr/db/markdowndb/markdown.db
      - MARKDOWN_DB_ROOT=/usr/db/markdowndb 

    volumes:
      - ./studybed-api:/usr/src/app
      - /usr/src/app/node_modules/
      - ./markdowndb:/usr/db/markdowndb
    ports:
      - "3000:3000"


