services:
  front:
    build: ./studybed-app
    command: "npm run start"
    environment:
      - PORT=${FRONTEND_PORT}
      - HOST=0.0.0.0
      - BACKEND_BROWSER_API=http://localhost:${BACKEND_PORT}
      - BACKEND_SERVER_API=http://backend:${BACKEND_PORT}
    volumes:
      - ./studybed-app:/usr/src/app
      - /usr/src/app/node_modules/
    ports:
      - "4200:${FRONTEND_PORT}"
    depends_on:
      - backend

  backend:
    build: ./studybed-api
    command: "npm run start:dev"
    environment:
      - PORT=${BACKEND_PORT}
      - HOST=0.0.0.0
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres-db:${POSTGRES_PORT}/${POSTGRES_DB}?schema=public
      # - MARKDOWN_DB_PATH=file:/usr/db/markdowndb/markdown.db
      # - MARKDOWN_DB_ROOT=/usr/db/markdowndb 
    volumes:
      - ./studybed-api:/usr/src/app
      - /usr/src/app/node_modules/
    ports:
      - "3000:${BACKEND_PORT}"
    depends_on:
      - postgres-db

  postgres-db:
    image: postgres
    volumes:
      - ./postgres-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}  
      - POSTGRES_PORT=${POSTGRES_PORT}
    ports:
      - "5432:${POSTGRES_PORT}"
